config/routes.rb
Rails.application.routes.draw do
  
  resources :locations
  devise_for :users
  root to: 'venues#index'

  get '/venues', to: 'venues#index', as: 'venues'
  post '/venues', to: 'venues#create'

  get '/venues/new', to: 'venues#new', as: 'new_venue'
  get '/venues/:id/edit', to: 'venues#edit', as: 'edit_venue'
  patch '/venues/:id', to: 'venues#update'
  get '/venues/:id', to: 'venues#show', as: 'venue'
  delete '/venues/:id', to: 'venues#destroy'
  get '/venues/:id/inventories', to: 'inventories#index', as: 'inventories'
  post '/venues/:id/inventories', to: 'inventories#create'
  get  '/venues/:id/inventories/new', to: 'inventories#new', as: 'new_venue_inventory'
  get  '/venues/:id/inventories/:vd/edit', to: 'inventories#edit', as: 'edit_venue_inventory'
  get  '/venues/:id/inventories/:vd', to: 'inventories#show', as: 'venue_inventory'
  put  '/venues/:id/inventories/:vd', to: 'inventories#update',as: 'inventory_update'
  delete  '/venues/:id/inventories/:vd', to: 'inventories#destroy',as: 'inventory_delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord

mount_uploader :image, ImageUploader
end

app/models/location.rb
class Location < ApplicationRecord

geocoded_by :address
after_validation :geocode , :if => :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
has_many  :inventories, dependent: :destroy

geocoded_by :address

after_validation :geocode, :if => :address_changed?




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :find_venue
  before_action :find_invent, only: [:update,:destroy]
  # GET /inventories
  # GET /inventories.json
  def index
  
    @inventories = @venue.inventories

  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
@inventory = @venue.inventories.find(params[:vd])  

  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
    @inventory = @venue.inventories.find(params[:vd])
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.venue_id = @venue.id
    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_url, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventories_url, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_venue
      @venue = Venue.find(params[:id])
    end

    def find_invent
    @inventory = Inventory.find(params[:vd])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:name, :price,:image, :category)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user! , except: [:show , :index]
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/inventories/_form.html.erb
<%= form_for @inventory, html: {multipart: true} do |f| %>
<% if @inventory.errors.any? %>
<div id="error_explanation">
	  <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>
 
      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </div>
  <div class= "field">
  <%= f.label :category %><br>
  <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
 <%= form_for Inventory.new , url: url_for(:controller => 'inventories', :action => 'update'), :html=> {:method => :put} do |f| %>
 

      <%= f.label :name %><br>
      <%= f.text_field :name %>

      <%= f.label :price %><br>
      <%= f.text_field :price %>
      <%= f.label :category %><br>
      <%= f.text_field :category %>
      <%= f.label :image %><br>
    <%= f.file_field :image %>
    <br>
      <%= f.submit "Save changes"%>
    <% end %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>inventories of <%= @venue.name %></h1>

<table>
  

  <tbody>
    <% @inventories.each do |invent| %>
      <tr>
        <td><%= image_tag invent.image.thumb.url.to_s %> </td>
        <td><%= invent.name %></td>
        <td><%= invent.price %></td>
        <td><%= invent.category %> </td>
        <td><%= link_to 'Show', :controller => 'inventories', :action => 'show', :id=>@venue.id ,:vd => invent.id%></td>
       <td> <%= link_to 'Edit', :controller => 'inventories', :action => 'edit',:vd => invent.id%> </td>
       <td><%= link_to 'Destroy', :controller => 'inventories', :action => 'destroy',:vd => invent.id, method: :delete,data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <td><%= link_to 'New', :controller => 'inventories', :action => 'new', :id=> @venue.id %></td>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @inventory.image.thumb.url %>
</p>
<p>
  <strong>Name:</strong>
  <%= @inventory.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>
<p>
  <strong>category:</strong>
  <%= @inventory.category %>
</p>

 <%= link_to 'Edit', :controller => 'inventories', :action => 'edit',:vd => @inventory.id%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mposnew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<h1>edit location</h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<h1>All locations</h1>
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<h1>Location</h1>
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(9000) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/venues/_form.html.erb
<%= form_for(venue) do |f| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Venues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<%= link_to 'show_inventory',inventories_path %>
<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>